---
language: node_js

before_script:
  - "sh git branch"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - "npm install"
  - "echo $TRAFFICSCORE_QA_ENV"

script:
  - npm test